/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class MerkleTreeWrapper {
  constructor(leaves: Array<Array<number>>)
  getRoot(): Array<number>
  getNodes(): Array<Array<Array<number>>>
  getLeaves(): Array<Array<number>>
  generateProof(leafIndex: number): Array<Array<number>> | null
  toProtobuf(): Array<number>
  static fromProtobuf(bytes: Uint8Array): MerkleTreeWrapper
  /** build a "bytes32" equivalent padded leaf containing seven numbers */
  static numbersToLeaf(numbers: Array<number>): Array<number>
  /** convert a "bytes32" equivalent padded leaf back to original number array */
  static leafToNumbers(encodedLeaf: Array<number>): Array<number>
}
